#ifndef _PROGSTATECONSTS_HPP
#define _PROGSTATECONSTS_HPP

#define _STATEHELP 'h'
#define _STATEQUIT 'q'
#define _STATEKEYLEFT KEY_LEFT
#define _STATEKEYRIGHT KEY_RIGHT
#define _STATEKEYUP KEY_UP
#define _STATEKEYDOWN KEY_DOWN
#define _ALLMOUSEEVENTS ALL_MOUSE_EVENTS
#define _MOUSEPOSITIONS REPORT_MOUSE_POSITION
#define _WINRESIZEEVENT 410

#endif // _PROGSTATECONSTS_HPP
